### ISSUE TITLE
Video resolution setting

### ISSUE THREAD

**Issue by Dazr** [ca0abinary/plugin.video.jwtv-unofficial#1]
Hi,

Is it possible to add another resolution (such as 360p)?  Or to change the current low resolution mode to 360p?

The ideal would be to allow the user choose between the current tv.jw.org resolution settings (240p, 360p, 480p, 720p, 1080).

However, if this is too time consuming to implement, changing the current lowest resolution to 360p would be ok.  240p looks terrible on a 40 inch TV.  360p is ok.  Or even if 3 are possible (240p, 360p, and one of the higher resolutions).

Thanks for your effort with this plugin!

**Comment by ca0abinary** [comment]
Resolution is now selectable!

**Comment by Dazr** [comment]
Thanks a lot for adding the selectable resolution functionality!

On Thu, Mar 19, 2015 at 12:21 PM, Jonathan DeMarks <notifications@github.com
