### ISSUE TITLE
Subtitles always displayed - monthly JW broadcast

### ISSUE THREAD

**Issue by Dazr** [ca0abinary/plugin.video.jwtv-unofficial#10]
Hi,

First I want to say thanks for your work on this plugin, I use it extensively for watching the monthly broadcast and other videos.

For quite a few months now, when watching the monthly broadcast (in English), subtitles are always displayed, in spite of the fact that I haven't set subtitles on.  I have tested this on both Kodi 17 and older versions of Kodi, it is the same.  I have also tested it on both a RPi 3, and Wetek Play, and both show the subtitles.  The region I am in is New Zealand/Australia.

I have tried to find a way to turn them off, but it is not possible, they are not set as being on.  After a while the subtitles get a little annoying when watching the hour long broadcast :-)

Thanks for having a look into this,
Darryl.

**Comment by ca0abinary** [comment]
Hi Darryl,

I'm glad you enjoy using the plugin! The version in the Kodi repository might be a little older than the latest release here on GitHub. Could you try downloading [this version](https://github.com/ca0abinary/plugin.video.jwtv-unofficial/archive/1.8.3.1.zip) using the "install from zip file" features and let me know if it fixes your problem? If so, I'll submit it to the main repository so everyone can benefit.

**Comment by Dazr** [comment]
Hi,

Thanks for the reply.  The version in the Kodi repository was a bit older than the latest version on Github, as you said.  So I installed the Github version and yes the problem is now fixed!  No more subtitles appearing.  Tested on Kodi 17/libreelec 8 on Rpi 3 and an older Kodi version on Wetek Play.  Thanks again!

**Comment by ca0abinary** [comment]
Thanks! I've started the process to get the updated version into the Kodi repository.
