### ISSUE TITLE
Streaming category and sub-categories 

### ISSUE THREAD

**Issue by gregorypilar** [ca0abinary/plugin.video.jwtv-unofficial#2]
HI,

On the first category (Streaming) If I click one of the subcategory? il will play all the videos on that category?  o will let me choose?

**Comment by ca0abinary** [comment]
It will behave like the website (http://tv.jw.org/) and play all the videos for that category, but starting at the "broadcast time" so you may jump into the middle of a video.

**Comment by gregorypilar** [comment]
Thanks
