### ISSUE TITLE
Cannot select language

### ISSUE THREAD

**Issue by benchdollar** [ca0abinary/plugin.video.jwtv-unofficial#3]
I just installed a fresh OpenELEC system and the JW Broadcasting plugin (many thanks!). It works so far, but I cannot select the language. The list of languages appears but then nothing happens when I select e.g. German. (The same behaviour is with OSMC). My hardware platform is a Raspberry Pi Model B.

**Comment by ca0abinary** [comment]
@benchdollar I could not reproduce this issue.

#### Steps taken:
1. On a Raspberry Pi B+ (512MB) I installed the latest stable build of OpenElec
2. Installed JW Broadcasting plugin
3. Set the language to German (used mouse to click it)
4. Clicked "Neuste Videos"
5. Clicked "Vor Alteren hab ich Respekt"
6. Video played in the German language

I did notice an issue where the man menu does not update the language until after the plugin is exited and re-entered all other menus seem to be in the correct language immediately. Is that the issue you've noticed or do videos continue to play in English?
