### ISSUE TITLE
No video in english

### ISSUE THREAD

**Issue by RubSteels** [ca0abinary/plugin.video.jwtv-unofficial#5]
I've just noticed that the plugin is not showing any category or video when english language is selected.

**Comment by ca0abinary** [comment]
@RubSteels I can't reproduce this issue, could you let me know what version of Kodi you are running and on what platform? Thanks!

**Comment by RubSteels** [comment]
I'm running Kodi 15.2 on QNAP HD Station 3.1.0.

Right now also all other languages are broken.
When i start the add on I only have the option to set a different language, but whatever language I select I do not get the list of options I was getting before (Streaming, Video on demand...)

**Comment by ca0abinary** [comment]
@RubSteels Could you attach your log file so I can see the error? I'm guessing it would be in the Linux location:
`$HOME/.kodi/temp/kodi.log`
but a guide to all the usual locations can be found here: http://kodi.wiki/view/Log_file/Advanced#Location

**Comment by RubSteels** [comment]
Good news, I solved the problem by deleting Kodi and reinstalling everything from scratch.

The fact that the plugin started having problems only in English misled me, because it happened just after the annual meeting and I assumed that the website was changed.
I should have realized that it was my problem after everything else stopped working.

Thank you very much for your availability.
