### ISSUE TITLE
Is there an RSS Feed

### ISSUE THREAD

**Issue by benny-danny** [ca0abinary/plugin.video.jwtv-unofficial#7]
How does this plugin get the latest videos? Is there a RSS feed I can watch to get noticed when there is a new video?

Thanks in advance!

**Comment by ca0abinary** [comment]
The program makes use of a public but undocumented API that the website uses. It's a RESTful JSON service that's good for this program but it's very easy to track new additions with. It isn't RSS or Atom or really anything you could hook up to a newsreader type application.
