### ISSUE TITLE
Streams now that there are Subtitled videos

### ISSUE THREAD

**Issue by molly78** [ca0abinary/plugin.video.jwtv-unofficial#8]
Good Day,

Any chance of an update to be able to select the non-subtitled broadcasts?

Huge thanks,

**Comment by ca0abinary** [comment]
Not on a video-per-video basis. Subtitles are turned on or off via a plugin option.

**Comment by molly78** [comment]
I have disabled subtitles fully throughout openelec on my PI
The broadcaster seems to reference a different file starting June and July

burnt in subs:
jwb_s-sub_E_201606_01_r720P.mp4

no subs
jwb_E_201606_01_r720P.mp4

huge thanks once again

**Comment by ca0abinary** [comment]
The option is on the plugin itself (not a system option) alongside the setting for video resolution. This is from the user guide on the Kodi website, hopefully it is helpful:

> Various add-ons also have settings that can be accessed by going to the Add-on manager: Settings -> Add-ons -> Enabled add-ons -> the add-on category -> the add-on title -> Configure

>You can also access add-on settings for some add-ons by bringing up the contextual menu press >guide on remote or C or ⊞ Win on a keyboard while using that add-on.

**Comment by molly78** [comment]
Correct and that option under the broadcaster config is off as well :)

The script is picking up a separate video that has hardcoded subs in it

https://download-a.akamaihd.net/files/media_broadcasting/7e/jwb_s-Sub_E_201606_01_r720P.mp4
vs
https://download-a.akamaihd.net/files/media_broadcasting/7e/jwb_E_201606_01_r720P.mp4

Much thanks for your help with this - I've disabled subtitles everywhere I could find

**Comment by ca0abinary** [comment]
Unfortunately my time is limited right now, would you consider using the prior version?
https://github.com/ca0abinary/plugin.video.jwtv-unofficial/archive/1.8.2.zip

This has all the same features except for subtitles are not available. If you continue to have problems, please let me know. I'll make some time to look at it.

**Comment by ca0abinary** [comment]
Subtitles have been fixed in the latest release.
